export const SkeletronEducationData = [
  {
    lessonTitle: 'Loading',
    lessonExperience: 0,
    module: 0,
    chapter: 0,
    lessonPath: 'Loading',
    passed: false,
    progress: 0,
    color: 'gray',
    lessonID: '0',
    lessonSubtitle: 'Loading',
  },
  {
    lessonTitle: 'Loading',
    lessonExperience: 0,
    module: 0,
    chapter: 0,
    lessonPath: 'Loading',
    passed: false,
    progress: 0,
    color: 'gray',
    lessonID: '1',
    lessonSubtitle: 'Loading',
  },
  {
    lessonTitle: 'Loading',
    lessonExperience: 0,
    module: 0,
    chapter: 0,
    lessonPath: 'Loading',
    passed: false,
    progress: 0,
    color: 'gray',
    lessonID: '2',
    lessonSubtitle: 'Loading',
  },
  {
    lessonTitle: 'Loading',
    lessonExperience: 0,
    module: 0,
    chapter: 1,
    lessonPath: 'Loading',
    passed: false,
    progress: 0,
    color: 'gray',
    lessonID: '3',
    lessonSubtitle: 'Loading',
  },
  {
    lessonTitle: 'Loading',
    lessonExperience: 0,
    module: 0,
    chapter: 1,
    lessonPath: 'Loading',
    passed: false,
    progress: 0,
    color: 'gray',
    lessonID: '4',
    lessonSubtitle: 'Loading',
  },
  {
    lessonTitle: 'Loading',
    lessonExperience: 0,
    module: 0,
    chapter: 1,
    lessonPath: 'Loading',
    passed: false,
    progress: 0,
    color: 'gray',
    lessonID: '5',
    lessonSubtitle: 'Loading',
  },
  {
    lessonTitle: 'Loading',
    lessonExperience: 0,
    module: 0,
    chapter: 2,
    lessonPath: 'Loading',
    passed: false,
    progress: 0,
    color: 'gray',
    lessonID: '6',
    lessonSubtitle: 'Loading',
  },
]